# Generated by Django 6.0.1 on 2026-01-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Қолданушы', 'verbose_name_plural': 'Қолданушылар'},
        ),
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(default=1, max_length=36, unique=True, verbose_name='ЖСН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Білім алушы'), ('manager', 'Менеджер')], default='learner', max_length=20, verbose_name='Типі'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='accounts/users/avatars', verbose_name='Аватар'),
        ),
    ]
