# Generated by Django 6.0.1 on 2026-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Тапсырушы'), ('manager', 'Менеджер')], default='customer', max_length=20, verbose_name='Типі'),
        ),
    ]
