# Generated by Django 6.0.1 on 2026-01-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтама')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ашық емтихан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
            ],
            options={
                'verbose_name': 'Емтихан',
                'verbose_name_plural': 'Емтихандар',
            },
        ),
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Тыңдалым (Listening)'), ('reading', 'Оқылым (Reading)'), ('speaking', 'Айтылым (Speaking)'), ('practical', 'Жазылым (Writing/Practical)')], default='listening', max_length=32, verbose_name='Секция түрі')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік')),
                ('max_score', models.PositiveSmallIntegerField(default=0, verbose_name='Макс. баллы')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=0, verbose_name='Уақыты (сек)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.exam', verbose_name='Емтихан')),
            ],
            options={
                'verbose_name': 'Емтихан секциясы',
                'verbose_name_plural': 'Емтихан секциялары',
            },
        ),
        migrations.CreateModel(
            name='ExamSectionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Мәтін')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exams/sounds/', verbose_name='Аудиожазба')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.examsection', verbose_name='Емтихан секциясы')),
            ],
            options={
                'verbose_name': 'Секция материалы',
                'verbose_name_plural': 'Секция материалдары',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq_single', 'Бір жауапты'), ('mcq_multi', 'Көп жауапты'), ('speaking_keywords', 'Айтылым'), ('practical_code', 'Жазбаша')], max_length=32, verbose_name='Сұрақ типі')),
                ('prompt', models.TextField(verbose_name='Берілгені')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Points')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.examsectionmaterial', verbose_name='Секция материалы')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.examsection', verbose_name='Емтихан секциясы')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list, verbose_name='Кілттік сөздер')),
                ('point_per_keyword', models.PositiveSmallIntegerField(default=3, verbose_name='Кілттік сөз баллы')),
                ('max_points', models.PositiveSmallIntegerField(default=25, verbose_name='Макс. балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_rubrics', to='core.question', verbose_name='Сұрақ')),
            ],
        ),
    ]
