# Generated by Django 6.0.1 on 2026-02-06 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exam_practicaltask_examsection_examsectionmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltask',
            name='input_spec',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='output_spec',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='question',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practical_task', to='core.question', verbose_name='Сұрақ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('checked', 'Checked')], default='in_progress', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='speaking_answers/')),
                ('transcript', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.option')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='multi_answers', to='core.option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Дерек енгізу')),
                ('expected_output', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.practicaltask', verbose_name='Тапсырма')),
            ],
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam', 'status'], name='core_examat_user_id_f5c358_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
