# Generated by Django 6.0.1 on 2026-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_practicaltask_input_spec_practicaltask_output_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager')], default='customer', max_length=16, verbose_name='Типі'),
        ),
    ]
