# Generated by Django 6.0.1 on 2026-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iin',
            field=models.CharField(max_length=36, unique=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Тапсырушы'), ('manager', 'Менеджер')], default='customer', max_length=16, verbose_name='Типі'),
        ),
    ]
