# Generated by Django 6.0.1 on 2026-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_examsection_time_limit_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ұпай'),
        ),
    ]
