# Generated by Django 6.0.1 on 2026-02-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsectionmaterial',
            name='time_limit_seconds',
        ),
        migrations.AddField(
            model_name='examsection',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уақыты (сек)'),
        ),
    ]
