# Generated by Django 6.0.1 on 2026-02-06 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_examsectionmaterial_time_limit_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'MCQ таңдау',
                'verbose_name_plural': 'MCQ таңдаулар',
            },
        ),
        migrations.CreateModel(
            name='PracticalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('js', 'JavaScript')], default='python', max_length=16, verbose_name='Тіл')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код')),
                ('passed', models.PositiveIntegerField(default=0, verbose_name='Өткен тест саны')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Құлаған тест саны')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Барлық тест саны')),
                ('runtime_ms', models.PositiveIntegerField(default=0, verbose_name='Runtime (ms)')),
                ('memory_kb', models.PositiveIntegerField(default=0, verbose_name='Memory (kb)')),
                ('verdict', models.CharField(blank=True, max_length=64, null=True, verbose_name='Verdict')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Толық нәтиже (JSON)')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Тексерілген уақыты')),
            ],
            options={
                'verbose_name': 'Practical жіберілім',
                'verbose_name_plural': 'Practical жіберілімдер',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_json', models.JSONField(blank=True, default=dict, verbose_name='Жауап (JSON)')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ұпай')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс ұпай')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Жауап берілді')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Бағаланды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
            ],
            options={
                'verbose_name': 'Сұрақ жауабы (QuestionAttempt)',
                'verbose_name_plural': 'Сұрақ жауаптары (QuestionAttempts)',
            },
        ),
        migrations.CreateModel(
            name='SectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Басталды (Draft)'), ('submitted', 'Жіберілді (Submitted)'), ('graded', 'Бағаланды (Graded)'), ('cancelled', 'Болдырылмады (Cancelled)')], default='draft', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Секция баллы')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс секция баллы')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Жұмсаған уақыт (сек)')),
            ],
            options={
                'verbose_name': 'Секция тапсыруы (SectionAttempt)',
                'verbose_name_plural': 'Секция тапсырулары (SectionAttempts)',
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exams/speaking/', verbose_name='Аудио жауап')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Транскрипт')),
                ('stt_provider', models.CharField(blank=True, max_length=64, null=True, verbose_name='STT провайдер')),
                ('stt_confidence', models.FloatField(blank=True, null=True, verbose_name='STT сенімділігі')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='Рубрика breakdown')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Кері байланыс')),
                ('grading_status', models.CharField(choices=[('draft', 'Басталды (Draft)'), ('submitted', 'Жіберілді (Submitted)'), ('graded', 'Бағаланды (Graded)'), ('cancelled', 'Болдырылмады (Cancelled)')], default='draft', max_length=16, verbose_name='Бағалау статусы')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Бағаланған уақыты')),
            ],
            options={
                'verbose_name': 'Speaking жауабы',
                'verbose_name_plural': 'Speaking жауаптары',
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='answer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_options',
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'Емтихан тапсыру (Attempt)', 'verbose_name_plural': 'Емтихан тапсырулар (Attempts)'},
        ),
        migrations.RemoveIndex(
            model_name='examattempt',
            name='core_examat_user_id_f5c358_idx',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='max_total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс жалпы балл'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Қосымша дерек'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Жалпы балл'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exam', verbose_name='Емтихан'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Басталған уақыты'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'Басталды (Draft)'), ('submitted', 'Жіберілді (Submitted)'), ('graded', 'Бағаланды (Graded)'), ('cancelled', 'Болдырылмады (Cancelled)')], default='draft', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam', 'started_at'], name='core_examat_user_id_2b0ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='core_examat_status_c2006b_idx'),
        ),
        migrations.AddField(
            model_name='mcqselection',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.option', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.question', verbose_name='Сұрақ'),
        ),
        migrations.AddField(
            model_name='practicalsubmission',
            name='question_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_submission', to='core.questionattempt', verbose_name='QuestionAttempt'),
        ),
        migrations.AddField(
            model_name='mcqselection',
            name='question_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_selections', to='core.questionattempt', verbose_name='QuestionAttempt'),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='core.examattempt', verbose_name='Attempt'),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.examsection', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='section_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='core.sectionattempt', verbose_name='SectionAttempt'),
        ),
        migrations.AddField(
            model_name='speakinganswer',
            name='question_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answer', to='core.questionattempt', verbose_name='QuestionAttempt'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='submitted_at',
        ),
        migrations.AddConstraint(
            model_name='mcqselection',
            constraint=models.UniqueConstraint(fields=('question_attempt', 'option'), name='uniq_mcq_selection'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['attempt', 'section'], name='core_sectio_attempt_f23d26_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['status'], name='core_sectio_status_e67f09_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'section'), name='uniq_section_attempt_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['section_attempt', 'question'], name='core_questi_section_6c970f_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['is_answered', 'is_graded'], name='core_questi_is_answ_8dee39_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('section_attempt', 'question'), name='uniq_question_attempt_per_section_attempt'),
        ),
    ]
