# Generated by Django 6.0.1 on 2026-02-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mcqselection_practicalsubmission_questionattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='material',
        ),
    ]
